/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Input_Indeks extends javax.swing.JFrame {

    /**
     * Creates new form Input_Indeks
     */
    public Input_Indeks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInputIndeks = new javax.swing.JLabel();
        lblKetIndeks = new javax.swing.JLabel();
        txtIndeksMhs = new javax.swing.JTextField();
        lblIndeksMhs = new javax.swing.JLabel();
        btnSubmitIndeks = new javax.swing.JButton();
        btnMenuUtamaDosen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInputIndeks.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInputIndeks.setText("Input Indeks");

        lblKetIndeks.setText("Ket. Indeks yang dapat dimasukkan adalah A/B/C/D/E");

        txtIndeksMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndeksMhsActionPerformed(evt);
            }
        });

        lblIndeksMhs.setText("Indeks Mahasiswa");

        btnSubmitIndeks.setText("Submit");

        btnMenuUtamaDosen.setText("Menu Utama");
        btnMenuUtamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtamaDosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMenuUtamaDosen)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIndeksMhs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIndeksMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(btnSubmitIndeks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblInputIndeks))
                    .addComponent(lblKetIndeks))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblInputIndeks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKetIndeks)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndeksMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIndeksMhs))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitIndeks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnMenuUtamaDosen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIndeksMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndeksMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndeksMhsActionPerformed

    private void btnMenuUtamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuUtamaDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Indeks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Indeks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Indeks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Indeks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Indeks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuUtamaDosen;
    private javax.swing.JButton btnSubmitIndeks;
    private javax.swing.JLabel lblIndeksMhs;
    private javax.swing.JLabel lblInputIndeks;
    private javax.swing.JLabel lblKetIndeks;
    private javax.swing.JTextField txtIndeksMhs;
    // End of variables declaration//GEN-END:variables

    public void setBtnMenuUtamaDosen(JButton btnMenuUtamaDosen) {
        this.btnMenuUtamaDosen = btnMenuUtamaDosen;
    }

    public void setBtnSubmitIndeks(JButton btnSubmitIndeks) {
        this.btnSubmitIndeks = btnSubmitIndeks;
    }

    public void setTxtIndeksMhs(JTextField txtIndeksMhs) {
        this.txtIndeksMhs = txtIndeksMhs;
    }

    public JButton getBtnMenuUtamaDosen() {
        return btnMenuUtamaDosen;
    }

    public JButton getBtnSubmitIndeks() {
        return btnSubmitIndeks;
    }

    public String getTxtIndeksMhs() {
        return txtIndeksMhs.getText();
    }
    
    public void addListener(ActionListener e){
        btnMenuUtamaDosen.addActionListener(e);
        btnSubmitIndeks.addActionListener(e);
    }
    
    public void showMessage(Component c, String s){
            JOptionPane.showMessageDialog(c,s);
    };

   

}
