/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Input_Token extends javax.swing.JFrame {

    /**
     * Creates new form Input_Token
     */
    public Input_Token() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKonfirmasiTkn = new javax.swing.JLabel();
        lblInputToken = new javax.swing.JLabel();
        txtInputToken = new javax.swing.JTextField();
        btnSubmitToken = new javax.swing.JButton();
        btnMenuUtamaMhs = new javax.swing.JButton();
        txtToken = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKonfirmasiTkn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblKonfirmasiTkn.setText("Konfirmasi Token Pembayaran");

        lblInputToken.setText("Input Token");

        btnSubmitToken.setText("Submit");
        btnSubmitToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitTokenActionPerformed(evt);
            }
        });

        btnMenuUtamaMhs.setText("Menu Utama");

        txtToken.setEditable(false);

        txtStatus.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(582, Short.MAX_VALUE)
                        .addComponent(btnMenuUtamaMhs))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(lblKonfirmasiTkn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtToken)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInputToken)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSubmitToken)
                                            .addComponent(txtInputToken, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblKonfirmasiTkn)
                .addGap(18, 18, 18)
                .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInputToken)
                    .addComponent(txtInputToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitToken)
                .addGap(34, 34, 34)
                .addComponent(btnMenuUtamaMhs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Token.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Token.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Token.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Token.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Token().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuUtamaMhs;
    private javax.swing.JButton btnSubmitToken;
    private javax.swing.JLabel lblInputToken;
    private javax.swing.JLabel lblKonfirmasiTkn;
    private javax.swing.JTextField txtInputToken;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables

    public void setBtnMenuUtamaMhs(JButton btnMenuUtamaMhs) {
        this.btnMenuUtamaMhs = btnMenuUtamaMhs;
    }

    public void setBtnSubmitToken(JButton btnSubmitToken) {
        this.btnSubmitToken = btnSubmitToken;
    }

    public void setTxtInputToken(JTextField txtInputToken) {
        this.txtInputToken = txtInputToken;
    }

    public void setTxtStatus(String s) {
        this.txtStatus.setText(s);
    }

    public void setTxtToken(String s) {
        this.txtToken.setText(s);
    }

    public JButton getBtnSubmitToken() {
        return btnSubmitToken;
    }

    public JButton getBtnMenuUtamaMhs() {
        return btnMenuUtamaMhs;
    }

    public String getTxtInputToken() {
        return txtInputToken.getText();
    }
    
    public void addListener(ActionListener e){
        btnMenuUtamaMhs.addActionListener(e);
        btnSubmitToken.addActionListener(e);
    }
    
    public void showMessage(Component c, String s){
            JOptionPane.showMessageDialog(c,s);
    };


}
