/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class Input_Absen extends javax.swing.JFrame {

    /**
     * Creates new form Input_Absen
     */
    public Input_Absen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInputAbsenMhs = new javax.swing.JLabel();
        tabKelas = new javax.swing.JTabbedPane();
        panelKelas01 = new javax.swing.JPanel();
        scrollPaneInputAbsenKls01 = new javax.swing.JScrollPane();
        tabelKls01 = new javax.swing.JTable();
        panelKelas02 = new javax.swing.JPanel();
        scrollPaneInputAbsenKls02 = new javax.swing.JScrollPane();
        tabelKls02 = new javax.swing.JTable();
        btnMenuUtamaMhs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInputAbsenMhs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInputAbsenMhs.setText("Input Absen Mahasiswa");

        tabelKls01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "KLS", "MATA KULIAH", "ABSEN"
            }
        ));
        scrollPaneInputAbsenKls01.setViewportView(tabelKls01);

        javax.swing.GroupLayout panelKelas01Layout = new javax.swing.GroupLayout(panelKelas01);
        panelKelas01.setLayout(panelKelas01Layout);
        panelKelas01Layout.setHorizontalGroup(
            panelKelas01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKelas01Layout.createSequentialGroup()
                .addComponent(scrollPaneInputAbsenKls01, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKelas01Layout.setVerticalGroup(
            panelKelas01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelas01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneInputAbsenKls01, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabKelas.addTab("Kelas 01", panelKelas01);

        tabelKls02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "KLS", "MATA KULIAH", "ABSEN"
            }
        ));
        scrollPaneInputAbsenKls02.setViewportView(tabelKls02);

        javax.swing.GroupLayout panelKelas02Layout = new javax.swing.GroupLayout(panelKelas02);
        panelKelas02.setLayout(panelKelas02Layout);
        panelKelas02Layout.setHorizontalGroup(
            panelKelas02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelas02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneInputAbsenKls02, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKelas02Layout.setVerticalGroup(
            panelKelas02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelas02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneInputAbsenKls02, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabKelas.addTab("Kelas 02", panelKelas02);

        btnMenuUtamaMhs.setText("Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lblInputAbsenMhs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabKelas)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMenuUtamaMhs)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInputAbsenMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuUtamaMhs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuUtamaMhs;
    private javax.swing.JLabel lblInputAbsenMhs;
    private javax.swing.JPanel panelKelas01;
    private javax.swing.JPanel panelKelas02;
    private javax.swing.JScrollPane scrollPaneInputAbsenKls01;
    private javax.swing.JScrollPane scrollPaneInputAbsenKls02;
    private javax.swing.JTabbedPane tabKelas;
    private javax.swing.JTable tabelKls01;
    private javax.swing.JTable tabelKls02;
    // End of variables declaration//GEN-END:variables

    public void setBtnMenuUtamaMhs(JButton btnMenuUtamaMhs) {
        this.btnMenuUtamaMhs = btnMenuUtamaMhs;
    }

    public JButton getBtnMenuUtamaMhs() {
        return btnMenuUtamaMhs;
    }
    
    public void addListener(ActionListener e){
        btnMenuUtamaMhs.addActionListener(e);
    }
    
    public void showMessage(Component c, String s){
            JOptionPane.showMessageDialog(c,s);
    };

}
