/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Absensi;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Input_Absen extends javax.swing.JFrame {

    /**
     * Creates new form Input_Absen
     */
    public Input_Absen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInputAbsenMhs = new javax.swing.JLabel();
        btnMenuUtamaMhs = new javax.swing.JButton();
        scrollPaneInputAbsenKls02 = new javax.swing.JScrollPane();
        tabelAbsen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInputAbsenMhs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInputAbsenMhs.setText("Input Absen Mahasiswa");

        btnMenuUtamaMhs.setText("Menu Utama");

        tabelAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idAbsensi", "idJadwal", "nim", "absen", "tidakAbsen"
            }
        ));
        scrollPaneInputAbsenKls02.setViewportView(tabelAbsen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lblInputAbsenMhs))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneInputAbsenKls02, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenuUtamaMhs)
                        .addGap(9, 9, 9)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInputAbsenMhs)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneInputAbsenKls02, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuUtamaMhs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold detabelAbsen="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuUtamaMhs;
    private javax.swing.JLabel lblInputAbsenMhs;
    private javax.swing.JScrollPane scrollPaneInputAbsenKls02;
    private javax.swing.JTable tabelAbsen;
    // End of variables declaration//GEN-END:variables

    public void setBtnMenuUtamaMhs(JButton btnMenuUtamaMhs) {
        this.btnMenuUtamaMhs = btnMenuUtamaMhs;
    }

    public JButton getBtnMenuUtamaMhs() {
        return btnMenuUtamaMhs;
    }
    
    public void addListener(ActionListener e){
        btnMenuUtamaMhs.addActionListener(e);
    }
    
    public void showMessage(Component c, String s){
            JOptionPane.showMessageDialog(c,s);
    };

    public void viewAbsen(ArrayList<Absensi> absen){
        String[] title = {"idAbsensi", "idJadwal", "nim", "absen", "tidakAbsen"};
        Object data[][] = new Object[absen.size()][5];
        int i = 0;
        for(Absensi a : absen){
            data[i][0] = (Integer) a.getIdAbsensi();
            data[i][1] = (Integer) a.getIdJadwal();
            data[i][2] = (Integer) a.getNim();
            data[i][3] = (String) a.getAbsen();
            data[i][4] = (String) a.getTidakAbsen();
            i++;
        }
        tabelAbsen.setModel(new DefaultTableModel(data, title));
    }
}
